#pragma once
static const char INDEX_HTML[] = R"HTML(<!doctype html>
<html lang="bn">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Bangla OLED Lyrics</title>
<style>
:root{color-scheme:dark;--bg:#0b1220;--card:#121d30;--line:#263852;--blue:#2f8cff;--green:#39d98a;--text:#edf4ff;--muted:#9fb0c7}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(145deg,#09111f,#111c2e 55%,#0b1322);color:var(--text);font-family:system-ui,-apple-system,"Noto Sans Bengali",sans-serif;min-height:100vh}
.wrap{max-width:760px;margin:auto;padding:22px 16px 42px}.hero{text-align:center;padding:20px 8px 18px}.hero h1{font-size:clamp(25px,6vw,38px);margin:0 0 8px}.hero p{color:var(--muted);margin:0}.card{background:rgba(18,29,48,.94);border:1px solid var(--line);border-radius:18px;padding:18px;margin:14px 0;box-shadow:0 12px 30px #0003}.card h2{font-size:20px;margin:0 0 14px}.statusbox{display:flex;gap:12px;align-items:flex-start;background:#0c1728;border:1px solid var(--line);border-radius:12px;padding:13px;margin-top:15px}.dot{width:11px;height:11px;border-radius:50%;background:#ffb020;margin-top:5px;flex:none}.dot.on{background:var(--green);box-shadow:0 0 12px var(--green)}.label{color:var(--muted);font-size:13px}.ip{font-size:18px;font-weight:700;word-break:break-all}.hint{font-size:13px;color:var(--muted);line-height:1.55}.row{display:flex;gap:9px}.row>*{flex:1}label{display:block;font-size:14px;color:var(--muted);margin:10px 0 5px}input,textarea,button{width:100%;font:inherit;border-radius:10px;padding:12px}input,textarea{background:#0b1525;color:var(--text);border:1px solid #38506e}textarea{height:250px;resize:vertical;line-height:1.45}button{border:0;background:var(--blue);color:#fff;font-weight:750;cursor:pointer;margin-top:10px;transition:.15s}button:hover{filter:brightness(1.12)}button.secondary{background:#263c5a}button.danger{background:#61364a}.primary{font-size:17px;padding:14px}.hidden{display:none!important}.file{padding:9px;background:#0b1525}.msg{min-height:24px;margin:12px 0 0;font-weight:650}.ok{color:var(--green)}.warn{color:#ffc857}.sectionhead{display:flex;justify-content:space-between;align-items:center;gap:10px}.sectionhead button{width:auto;margin:0;padding:8px 12px;font-size:13px}.badge{font-size:12px;color:var(--muted)}
</style></head>
<body><main class="wrap"><header class="hero"><h1>বাংলা Lyrics OLED</h1><p>ESP32 • SSD1315 • SRT থেকে 128×64 OLED</p></header>
<section class="card"><div class="sectionhead"><h2>ESP32 connection</h2><span class="badge" id="mode">Setup hotspot</span></div><div class="statusbox"><span class="dot" id="dot"></span><div><div class="label" id="stateText">Wi‑Fi status যাচাই হচ্ছে…</div><div class="ip" id="ipText">—</div><div class="hint" id="ipHint">Hotspot URL: http://192.168.4.1</div></div></div><div id="wifiPanel"><form id="wifi"><label for="ssid">Router Wi‑Fi name (SSID)</label><input id="ssid" required autocomplete="off" placeholder="আপনার Wi‑Fi নাম"><label for="pass">Wi‑Fi password</label><input id="pass" type="password" autocomplete="off" placeholder="Wi‑Fi password"><button class="primary">Wi‑Fi-তে যুক্ত করুন</button></form></div><div id="connectedPanel" class="hidden"><p class="hint">Wi‑Fi connected। এখন নিচের SRT convert করুন। Convert সফল হলে Wi‑Fi পরিবর্তনের option দেখা যাবে।</p><button id="change" class="secondary hidden">Wi‑Fi পরিবর্তন করুন</button></div><button id="forget" class="danger">Saved Wi‑Fi মুছে ফেলুন</button><p id="wifiMsg" class="msg"></p></section>
<section class="card"><h2>SRT থেকে OLED</h2><label for="file">SRT file নির্বাচন করুন</label><input id="file" class="file" type="file" accept=".srt,.txt"><label for="srt">অথবা সম্পূর্ণ SRT এখানে paste করুন</label><textarea id="srt" placeholder="এখানে SRT paste করুন…"></textarea><button id="send" class="primary">▶ Start Convert &amp; Send to OLED</button><p id="sendMsg" class="msg"></p><p class="hint">Convert চাপার সময় playback clock শুরু হবে। গানটি 0:00-তে pause করে রেখে success message দেখার সঙ্গে সঙ্গে Play করুন।</p></section>
<script>
const $=id=>document.getElementById(id);function text(el,s,c=''){el.textContent=s;el.className='msg '+c}function showConnect(v){$('wifiPanel').classList.toggle('hidden',!v);$('connectedPanel').classList.toggle('hidden',v)}
async function refresh(){try{let j=await (await fetch('/api/status',{cache:'no-store'})).json();let on=!!j.connected;$('dot').classList.toggle('on',on);$('stateText').textContent=on?'Router Wi‑Fi connected':'Setup hotspot active — router Wi‑Fi connect করুন';$('mode').textContent=on?'Ready for SRT':'Wi‑Fi setup';$('ipText').textContent=on?'Router IP: '+j.ip:'Open: http://'+j.ap;$('ipHint').textContent=on?'Phone-কে একই router Wi‑Fi-তে যুক্ত করে এই Router IP খুলুন। Setup URL: http://'+j.ap:'এই page খুলতে phone-কে ESP32-Bangla-OLED hotspot-এ যুক্ত করুন।';showConnect(!on)}catch(e){$('stateText').textContent='Status পাওয়া যাচ্ছে না'}}
$('file').onchange=async e=>{let f=e.target.files[0];if(f){$('srt').value=await f.text();text($('sendMsg'),'File loaded — এখন Start Convert চাপুন','ok')}};
$('wifi').onsubmit=async e=>{e.preventDefault();let b=new TextEncoder().encode('ssid='+encodeURIComponent($('ssid').value)+'&password='+encodeURIComponent($('pass').value));text($('wifiMsg'),'Connecting…');try{let r=await fetch('/api/wifi',{method:'POST',body:b});text($('wifiMsg'),await r.text(),r.ok?'ok':'warn');setTimeout(refresh,900)}catch(x){text($('wifiMsg'),'Connection request failed','warn')}};
$('change').onclick=()=>{showConnect(true);text($('wifiMsg'),'নতুন router-এর তথ্য দিন','ok');$('ssid').focus()};
$('forget').onclick=async()=>{if(confirm('Saved Wi‑Fi মুছে ফেলবেন?')){let r=await fetch('/api/forget',{method:'POST'});text($('wifiMsg'),await r.text(),r.ok?'ok':'warn');showConnect(true);setTimeout(refresh,400)}};
function ms(s){let [h,m,x]=s.replace(',','.').split(':');return Math.round((+h*3600+ +m*60+ +x)*1000)}
function parse(s){let a=s.replace(/\r/g,'').split('\n'),o=[];for(let i=0;i<a.length;){if(/^\d+$/.test(a[i].trim())&&a[i+1]&&a[i+1].includes('-->')){let t=a[i+1].split('-->');let text=[],j=i+2;while(j<a.length&&a[j].trim()!==''){text.push(a[j].trim());j++}o.push({a:ms(t[0].trim()),b:ms(t[1].trim()),t:text.join(' ')});i=j+1}else i++}return o}
function frame(t){let c=document.createElement('canvas');c.width=128;c.height=64;let x=c.getContext('2d');x.fillStyle='#000';x.fillRect(0,0,128,64);x.fillStyle='#fff';x.font='16px sans-serif';x.textAlign='center';x.textBaseline='top';let rows=[],cur='';for(let w of t.split(/\s+/)){let q=cur?cur+' '+w:w;if(x.measureText(q).width<=124||!cur)cur=q;else{rows.push(cur);cur=w}}if(cur)rows.push(cur);rows=rows.slice(0,3);let total=rows.length*18-2;rows.forEach((r,i)=>x.fillText(r,64,(64-total)/2+i*18));let im=x.getImageData(0,0,128,64).data,b=new Uint8Array(1024);for(let y=0;y<64;y++)for(let xx=0;xx<128;xx++)if(im[(y*128+xx)*4]>100)b[(y>>3)*128+xx]|=1<<(y&7);return b}
$('send').onclick=async()=>{let e=parse($('srt').value);if(!e.length)return text($('sendMsg'),'SRT timing পাওয়া যায়নি — file নির্বাচন বা SRT paste করুন','warn');if(e.length>64)return text($('sendMsg'),'সর্বোচ্চ 64টি subtitle entry পাঠানো যাবে','warn');let z=8+e.length*1034,b=new ArrayBuffer(z),v=new DataView(b),p=0;v.setUint32(p,0x4c595243,true);p+=4;v.setUint16(p,e.length,true);p+=2;v.setUint16(p,0,true);p+=2;text($('sendMsg'),'SRT '+e.length+'টি entry পাওয়া গেছে — bitmap তৈরি হচ্ছে…','ok');for(let q of e){v.setUint32(p,q.a,true);p+=4;v.setUint32(p,q.b,true);p+=4;v.setUint16(p,1024,true);p+=2;new Uint8Array(b,p,1024).set(frame(q.t));p+=1024}text($('sendMsg'),'Bitmap তৈরি হয়েছে — ESP32-তে পাঠানো হচ্ছে…');$('send').disabled=true;try{let r=await fetch('/api/lyrics',{method:'POST',body:b});let out=await r.text();text($('sendMsg'),out,r.ok?'ok':'warn');if(r.ok)$('change').classList.remove('hidden')}catch(x){text($('sendMsg'),'Send failed — ESP32 connection পরীক্ষা করুন','warn')}finally{$('send').disabled=false}};
refresh();setInterval(refresh,2500);
</script></main></body></html>)HTML";
